### ISSUE TITLE
Boost confirmation does not appear in context menu on Vivaldi Android

### ISSUE THREAD

**Issue by bchandos** [cheeaun/phanpy#197] opened 2023-07-26 16:10 UTC
**Describe the bug**
The "boost to everyone?" confirmation does not appear for me when using Vivaldi on Android in the context menu. It does appear when boosting from the post screen. It works on the same phone using Firefox.
- Which site: both dev.phanpy.social and phanpy.social
- Which instance: Mastodon.online

**To Reproduce**
1. Long press on a post to bring up the context overlay menu
2. Click on "Boost..."
3. Items reminds highlighted but confirmation does not appear

**Expected behavior**
Boost confirmation appears.

**Screenshots**
Firefox 
![Firefox on Android](https://github.com/cheeaun/phanpy/assets/5678326/6673ab88-49db-4841-8ed8-e3b0feeb52d7)

Vivaldi
![Vivaldi on Android](https://github.com/cheeaun/phanpy/assets/5678326/bd5f2a46-de37-4ca2-a98e-1805705af9c4)

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 13
 - Browser: Vivaldi Browser 6.1.3035.110

**Additional context**
I believe Vivaldi is using Chromium and just adds ad and tracker blocking. I tried turning off the blocking but it made no difference. I am not aware of any other plugins.

(P.S. this is a really great web app, I very much appreciate it!)

**Comment by bchandos** [comment] 2023-07-26 20:55
This is likely a more general issue with this style of confirmation modal as it also occurs when un-following a hashtag.

**Comment by bchandos** [comment] 2023-07-29 16:42
I did some remote debugging from Vivaldi on my laptop to Vivaldi on my phone. There were no console errors, and as best I can tell, the component simply is not being rendered into the DOM. Other DOM changes *do* occur, such as changes to `tabindex` and classes...

With context menu open, prior to pressing "Boost..."
![image](https://github.com/cheeaun/phanpy/assets/5678326/a962dec5-fb8f-4d3b-b87a-0998f6862345)

With context menu open, after pressing "Boost..."
![image](https://github.com/cheeaun/phanpy/assets/5678326/65fadd6b-bc63-4539-95a6-9e940a6d5ef6)

(P.S. I noticed that while connected to debugging, the issues became intermittent: I saw the submenu a few times in Vivaldi. However it mostly continued to behave as described.)

**Comment by bchandos** [comment] 2023-07-29 17:01
The intermittent behavior gave me a thought and so I tried spamming the button and eventually the submenu will appear. The number of presses is inconsistent.

I doubt this helps much but interesting nonetheless.

**Comment by cheeaun** [comment] 2023-07-31 05:30
@bchandos this seems very difficult for me to test too, can't reproduce this on Vivaldi browser on my Pixel 3 (Android 12). Just wondering if this also happens on other Chromium-based browsers on your phone? 🙏

**Comment by marcin-kozinski** [comment] 2023-08-02 19:15
I have the same issue on Chrome on my phone.

Chrome 115.0.5790.138
Android 14; Pixel 7a Build/UPB4.230623.007

**Comment by Alex0007** [comment] 2023-08-21 09:03
Does not appear in the latest Google Chrome (116). But works in the latest Firefox.

![Screenshot_20230821-130116.png](https://github.com/cheeaun/phanpy/assets/1143226/58d447f8-1237-4579-a3ba-a6297e84c9cb)

![Screenshot_20230821-130101.png](https://github.com/cheeaun/phanpy/assets/1143226/74b44f05-b766-4ad8-8147-3467721cee60)

**Comment by cheeaun** [comment] 2023-08-21 11:11
@Alex0007 is it on Android 13/14?

Everyone, I'm still unable to reproduce this bug on my Pixel 3 (Android 12). I've also tried it on the Android emulator with Android 13 image and couldn't reproduce this bug 😭

I [mentioned](https://mastodon.social/@cheeaun/110837119835026838) that it would be great if anyone could try debug this on own device and check what is actually happening 🙇‍♂️🙏

**Comment by Alex0007** [comment] 2023-08-21 12:04
@cheeaun 

When tapping with fingers on physical device – submenu element is not appearing in DOM at all.
When using on-screen tapping in Developer Tools (device is connected via wireless debugging) – this element appears normally

<details>
  <summary>Screenshots</summary>
  
After tapping boost menu item on device:
<img width="1169" alt="Screenshot 2023-08-21 at 16 00 52" src="https://github.com/cheeaun/phanpy/assets/1143226/a83bda08-c2de-4170-b68f-a784f1542f4b">

After tapping boost menu item via wireless debugging session
<img width="1169" alt="Screenshot 2023-08-21 at 15 58 20" src="https://github.com/cheeaun/phanpy/assets/1143226/91e5facf-b1e7-4919-a325-244c12d010ae">
  
</details>

**Comment by Alex0007** [comment] 2023-08-24 21:10
@cheeaun i noticed that "Boost to everyone?" disappears when cursor leaves "Boost" context menu area. Can it be somehow related with this issue?

**Comment by felix9** [comment] 2023-08-25 08:18
I can reproduce this about 20% of the time on my Pixel 3a.

I see a similar problem with the "Mute" option in the 3-dots menu for a user profile. About 80% of the time, pressing "Mute" does not show the submenu for mute duration.

**Comment by felix9** [comment] 2023-08-25 09:32
If I inspect the menu item's event listeners and remove the "pointermove" handler (which goes to a preact dispatcher), the submenu pops up reliably.

I'm not sure why that fixes it. This seems timing dependent, so hard to diagnose with breakpoints. I added some logpoints to the preact dispatcher and the submenu handler.

When I tap on the menu item, and the submenu doesn't show, the dispatcher events that look like:
pointerenter, pointermove, focusout, pointerleave, pointerleave, click, click
(sometimes focusout comes between the pointerleave)
neither click event triggers the submenu toggle.

when I tap on the menu item, and the submenu does show, the dispatcher events look like:
pointerenter, pointerleave, pointerleave, focusout, click, click
the second click event triggers submenu toggle

**Comment by osmaa** [comment] 2023-08-27 12:21
I can reproduce @Alex0007 finding with Android Chrome 116.0.5845.92:
- connect phone to USB debugging, open dev console on the computer for the Phanpy tab
- tapping boost option in popup menu does not trigger confirmation dialog on the phone
- but emulating finger on the dev console reproduction of the screen, boost confirmation IS triggered when clicking on the boost option

So what @felix9 describes seems plausible.

BTW, I'd prefer to disable the boost confirmation step entirely, but that's another thing..

**Comment by Alex0007** [comment] 2023-08-29 09:50
8bfc9892edcc52a1361dc31db9198cb224bad8d3

This commit resolved issue for me

**Comment by cheeaun** [comment] 2023-08-29 10:00
@Alex0007 thanks for clarifying! I honestly still can't reproduce this on my Pixel phone and I'm blindly _fixing_ this based on @felix9 investigations. `pointermove` is a surprising event triggered; tapping (down, up) shouldn't really trigger that unless there's a **very sensitive** sub-pixel movement when tapping down and up on the screen 🤔

Would be great to gather more feedback on this before marking this as fixed 🙏

**Comment by osmaa** [comment] 2023-08-30 06:23
dev.phanpy.social boost menu option now works for me, too.

**Comment by durka** [comment] 2023-08-31 04:25
Hi, came here to confirm the bug in Adblock Browser (versions below) and I can confirm the fix as well!

![Screenshot_20230831-002407](https://github.com/cheeaun/phanpy/assets/47007/65cdab0e-d838-4980-9683-25ec4f75e35f)

**Closed** 2023-11-08 02:26 UTC
Labels: bug, need investigation, unable to reproduce
