### ISSUE TITLE
Option to turn off "Boost to everyone" confirmation

### ISSUE THREAD

**Issue by eloquence** [cheeaun/phanpy#349] opened 2023-12-08 07:08 UTC
It's easy to un-boost something in case of accidental clicks - it'd be nice to have the option to disable the confirmation step, especially since boosts are already an extra click away (see post -> open post in expanded view -> click boost -> click "boost to everyone").

**Comment by cheeaun** [comment] 2023-12-09 07:45
Duplicate of https://github.com/cheeaun/phanpy/issues/186

**Closed by cheeaun** 2023-12-09 07:45 UTC
