### ISSUE TITLE
Boost context menu option is not working

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#218] opened 2023-08-18 03:28 UTC
**Describe the bug**
- Which site: dev.phanpy.social

**To Reproduce**
1. Go to feed
2. Open context menu from any post
3. Click Boost
4. See that nothing happened

**Screenshots**
![Screenshot_20230818-072341.png](https://github.com/cheeaun/phanpy/assets/1143226/daa173ef-ea09-4e59-90ac-096ecbccd003)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android 14
 - Browser Google Chrome
 - Version 116

**Comment by Alex0007** [comment] 2023-08-18 03:49
<img width="255" alt="Screenshot 2023-08-18 at 07 48 53" src="https://github.com/cheeaun/phanpy/assets/1143226/2f24c94b-8c21-4b00-b17c-ee379b130098">

This confirmation do not appear on mobile

**Comment by cheeaun** [comment] 2023-08-18 03:50
Duplicate of https://github.com/cheeaun/phanpy/issues/197

**Closed** 2023-08-18 03:58 UTC
